version: "1"

databases:
  # 1. Base de datos PostgreSQL
  - name: testing-agry-db
    plan: free

services:
  # 2. Web Service para el Backend (Node.js)
  - type: web
    name: testing-agry-backend
    env: node
    plan: free # Usa tier gratuito
    rootDir: "backend"
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: testing-agry-db
          property: connectionString
      - key: NODE_ENV
        value: production
      # Aquí puedes añadir el JWT_SECRET que vimos que podría usar tu app
      - key: JWT_SECRET
        generateValue: true

  # 3. Web Service Estático para el Frontend (React/Vite)
  - type: web
    name: testing-agry-frontend
    env: static
    rootDir: "frontend"
    buildCommand: "npm install && npm run build"
    # Vite genera por defecto en la carpeta dist (relativa a frontend)
    staticPublishPath: "./dist"
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: testing-agry-backend
          property: host
